const { chromium } = require('playwright');
const fs = require('fs'), path = require('path'), http = require('http');
const root = path.join(__dirname, '..');
const html = () => `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><style>:root{color-scheme:light}body{margin:0;font:14px system-ui}img{max-width:100%}[hidden]{display:none!important}</style></head><body>${fs.readFileSync(path.join(root, 'index.html'), 'utf8')}</body></html>`;
(async () => {
  const srv = http.createServer((q, r) => { r.setHeader('content-type', 'text/html; charset=utf-8'); r.end(html()); }).listen(0); const url = `http://127.0.0.1:${srv.address().port}/`;
  const b = await chromium.launch(); const errs = [];
  const c = await b.newContext({ viewport: { width: 402, height: 874 }, deviceScaleFactor: 2, colorScheme: 'dark' }); const p = await c.newPage();
  p.on('console', m => { if (m.type() === 'error' && !/ERR_|Failed to load resource/.test(m.text())) errs.push(m.text()); }); p.on('pageerror', e => errs.push('PAGEERROR ' + e.message));
  const shot = n => p.screenshot({ path: path.join(root, 'shots', n + '.png') });
  const st = () => p.evaluate(() => ({ mode: __demo.S.mode, n: __demo.db.sessions.length, mine: __demo.mine ? __demo.mine.sessions.length : null, bal: Calc.balances(__demo.db.stores, __demo.db.sessions).s1, budget: __demo.S.budget, ok: __demo.store.ok, bytes: (localStorage.getItem(__demo.KEY) || '').length, pill: document.querySelector('.top .pill').textContent }));
  await p.goto(url); await p.waitForTimeout(400);
  console.log('1 FIRST', JSON.stringify(await st())); await shot('s-sample');
  await p.click('[data-act="askMine"]'); await shot('s-ask'); await p.click('[data-act="useMine"]'); await p.waitForTimeout(200);
  console.log('2 MINE ', JSON.stringify(await st())); await shot('s-mine-empty');
  await p.click('.empty [data-act="editStore"]'); await p.fill('#sf-init', '1200'); await p.click('[data-act="saveStore"]'); await p.waitForTimeout(150);
  await p.click('#app [data-tab="add"]'); await p.waitForTimeout(250);
  await p.click('[data-act="pickMachine"][data-i="0"]'); await p.click('[data-act="chooseMachine"][data-id="m1"]');
  await p.fill('#f-p-0-cash', '5000'); await p.fill('#f-p-0-out', '600'); await p.click('[data-act="depSet"][data-v="all"]'); await p.click('[data-act="save"]'); await p.waitForTimeout(250);
  console.log('3 SAVED', JSON.stringify(await st())); await shot('s-mine-1');
  await p.click('#app [data-tab="more"]'); await p.click('#f-budget'); await p.keyboard.press('Control+A'); await p.keyboard.type('60000'); await p.keyboard.press('Tab'); await p.waitForTimeout(100); await shot('s-more');
  await p.reload(); await p.waitForTimeout(400);
  console.log('4 RELOAD', JSON.stringify(await st()), 'card', await p.evaluate(() => document.querySelector('#app .member img')?.naturalWidth));
  await p.click('#app [data-tab="more"]'); await p.click('[data-act="useSample"]'); await p.waitForTimeout(150);
  console.log('5 SAMPLE', JSON.stringify(await st()));
  await p.click('#app [data-act="askClear"]'); await p.click('[data-act="doClear"]'); await p.waitForTimeout(100);
  console.log('6 SAMPLE CLEARED', JSON.stringify(await st()));
  await p.reload(); await p.waitForTimeout(400);
  console.log('7 RELOAD(sample mode)', JSON.stringify(await st()));
  await p.click('#app [data-tab="more"]'); await p.click('[data-act="useMine"]'); await p.waitForTimeout(150);
  await p.click('#app [data-tab="more"]'); await p.click('[data-act="askWipe"]'); await shot('s-wipe'); await p.click('[data-act="doWipe"]'); await p.waitForTimeout(100);
  console.log('8 WIPED', JSON.stringify(await st()));
  await p.click('[data-act="undo"]'); await p.waitForTimeout(100);
  console.log('9 UNDO ', JSON.stringify(await st()));
  await p.evaluate(() => { const o = JSON.parse(localStorage.getItem(__demo.KEY)); o.body = o.body.slice(0, 50); localStorage.setItem(__demo.KEY, JSON.stringify(o)); __demo.store.ok = false; });
  await p.reload(); await p.waitForTimeout(400);
  console.log('10 BROKEN', JSON.stringify(await st()), 'kept', await p.evaluate(() => !!localStorage.getItem(__demo.KEY + '.broken')), 'toast', await p.evaluate(() => document.querySelector('#toast').textContent));
  console.log('ERRORS', JSON.stringify(errs)); await b.close(); srv.close();
})();
